import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { SocialProfileSimple } from "@/components/SocialProfileSimple/SocialProfileSimple";
import { child, get, ref } from "firebase/database";
import { database } from "@/services/firebase";
import { IDataPage } from "@/types/IDataPage";
import axios from "axios";
import { api } from "@/services/api";

const inter = Inter({ subsets: ["latin"] });
export const getServerSideProps = (async ({ params }) => {
  let dataPage = {} as IDataPage;
  if (!!params?.id) {
    const response = await api.get("/api/get-data-page", {
      params,
    });
    dataPage = response.data;
  }

  return {
    props: { dataPage },
  };
}) satisfies GetServerSideProps<{
  dataPage: IDataPage;
}>;

export default function Home({
  dataPage,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SocialProfileSimple dataPage={dataPage} />
      </main>
    </>
  );
}
