import Head from "next/head";

import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { SocialProfileSimple } from "@/components/SocialProfileSimple/SocialProfileSimple";

import { IDataPage } from "@/types/IDataPage";
import { api } from "@/services/api";
import { Center, Heading, Text } from "@chakra-ui/react";

export default function Home({
  dataPage,
  notFoundInfo,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Links | {dataPage["info-main"]?.name}</title>
        <meta
          name={dataPage["info-main"]?.resume}
          content="Generated by xulioguimarães"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/link.png" />
      </Head>
      <main>
        {!notFoundInfo && <SocialProfileSimple dataPage={dataPage} />}
        {notFoundInfo && (
          <Center flexDirection={"column"} h={"100vh"} py={2} w={"100%"}>
            <Text fontSize="18px" mt={3} mb={2}>
              Pagina não encontrada.
            </Text>
            <Text textAlign={"center"} color={"gray.500"} mb={6}>
              Não há informações cadastradas até o momento
            </Text>
          </Center>
        )}
      </main>
    </>
  );
}

export const getServerSideProps = (async ({ params }) => {
  let dataPage = {} as IDataPage;
  let notFoundInfo = false;

  if (!!params?.id) {
    const response = await api.get("/api/get-data-page", {
      params,
    });
    dataPage = response.data.data;
    notFoundInfo = response.data.notFoundInfo;
  }

  return {
    props: { dataPage, notFoundInfo },
  };
}) satisfies GetServerSideProps<{
  dataPage: IDataPage;
  notFoundInfo: boolean;
}>;
